/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.krisleonard.newrelic.project;

import com.krisleonard.newrelic.project.server.SocketServer;

/**
 * The New Relic coding project app
 */
public class App {

    /**
     * The client connection working queue size. Defaults to 200
     */
    private static final int CLIENT_CONNECTION_WORK_QUEUE_SIZE =
            Integer.parseInt(
                    System.getProperty("client.connection.queue.size", Integer.toString(200)));

    /**
     * The client connection pool size. Defaults to four
     */
    private static final int CLIENT_CONNECTION_POOL_SIZE = Integer.parseInt(
            System.getProperty("client.connection.pool.size", Integer.toString( 4)));

    /**
     * The client connection port. Defaults to 4000
     */
    private static final int CLIENT_CONNECTION_PORT = Integer.parseInt(
            System.getProperty("client.connection.port", Integer.toString( 4000)));

    public static void main(String[] args) {
        // Create the server
        SocketServer socketServer = new SocketServer();

        // Set a shutdown hook
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            socketServer.shutdown();
        }));

        // Start the server
        socketServer.startServer(CLIENT_CONNECTION_PORT,
                CLIENT_CONNECTION_POOL_SIZE, CLIENT_CONNECTION_WORK_QUEUE_SIZE);
    }
}
